---
version: 2

project_name: rklotz

builds:
  - id: binary-build
    main: main.go
    binary: rklotz
    ldflags:
      - -s -w -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

dockers_v2:
  - ids:
      - binary-build
    images:
      - vgarvardt/rklotz
    tags:
      - latest
      - "{{.Tag}}"
    platforms:
      - linux/amd64
      - linux/arm64
    dockerfile: Dockerfile
    extra_files:
      - static
      - templates
      - assets/posts
