FROM golang:1.8-alpine

# Install base packages
RUN apk update && apk upgrade && apk add \
    bash \
    curl \
    git \
    nodejs \
    vim

RUN go get -u github.com/Masterminds/glide
RUN npm install -g bower

RUN mkdir -p /go/src/github.com/vgarvardt/rklotz \
    && mkdir -p /data/bin \
    && mkdir -p /data/var \
    && mkdir -p /data/templates \
    && mkdir -p /data/static

WORKDIR /go/src/github.com/vgarvardt/rklotz

EXPOSE 8080
