FROM golang:1.7-alpine

# Install base packages
RUN apk update && apk upgrade && apk add \
    bash \
    curl \
    git \
    nodejs \
    vim

RUN curl https://glide.sh/get | sh
RUN npm install -g bower

RUN mkdir -p /go/src/github.com/vgarvardt/rklotz
RUN mkdir -p /data/bin
RUN mkdir -p /data/db
RUN mkdir -p /data/templates
RUN mkdir -p /data/static

WORKDIR /go/src/github.com/vgarvardt/rklotz

EXPOSE 8080
