---
version: "2"
linters:
  enable:
    - gocheckcompilerdirectives
    - goconst
    - gocritic
    - gosec
    - revive
    - sloglint
    - unconvert
    - whitespace
  settings:
    errcheck:
      check-blank: true
      exclude-functions:
        - io.Copy
        - fmt.Printf
        - bytes.Buffer.Write
    revive:
      enable-all-rules: false
      rules:
        - name: exported
          arguments:
            - disableStutteringCheck
          disabled: false
        - name: import-alias-naming
          arguments:
            - ^[a-z][a-zA-Z0-9]{0,}$
          disabled: false
        - name: context-as-argument
          disabled: false
        - name: import-shadowing
          disabled: false
        - name: var-declaration
          disabled: false
        - name: use-any
          disabled: false
        - name: cognitive-complexity
          arguments:
            - 30
          disabled: false
        - name: cyclomatic
          arguments:
            - 30
          disabled: false
        - name: line-length-limit
          arguments:
            - 180
          disabled: false
        - name: comment-spacings
          disabled: false
        - name: increment-decrement
          disabled: false
        - name: unhandled-error
          arguments:
            - fmt.Printf
            - io.Copy
            - bytes.Buffer.Write
          disabled: false
        - name: var-naming
          disabled: false
        - name: add-constant
          disabled: true
        - name: bare-return
          disabled: true
        - name: flag-parameter
          disabled: true
        - name: function-length
          disabled: true
        - name: unused-receiver
          disabled: true
        - name: max-public-structs
          disabled: true
        - name: unchecked-type-assertion
          disabled: true
        - name: function-result-limit
          disabled: true
        - name: confusing-naming
          disabled: true
        - name: get-return
          disabled: true
        - name: nested-structs
          disabled: true
        - name: argument-limit
          disabled: true
    staticcheck:
      checks:
        - all
        # Incorrect or missing package comment.
        # https://staticcheck.dev/docs/checks/#ST1000
        - "-ST1000"
        # Omit embedded fields from selector expression.
        # https://staticcheck.dev/docs/checks/#QF1008
        - "-QF1008"
  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: _test\.go
        linters:
          - dupl
          - goconst
          - gosec
          - staticcheck
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/vgarvardt/rklotz)
      custom-order: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
