---
###########################
###########################
## Markdown Linter rules ##
###########################
###########################

# Linter rules doc:
# - https://github.com/DavidAnson/markdownlint
#
# Note:
# To comment out a single error:
#   <!-- markdownlint-disable -->
#   any violations you want
#   <!-- markdownlint-restore -->
#

###############
# Rules by id #
###############
MD004: false                  # Unordered list style
MD007:
  indent: 2                   # Unordered list indentation
MD010:
  code_blocks: false          # Ignore no-hard-tabs in cde blocks because that's how formatting for golang works
MD013:
  line_length: 120            # Line length 80 is far too short
MD024:
  siblings_only: true         # Allow the same headers for different sections
MD026:
  punctuation: ".,;:!。，；:"  # List of not allowed
MD029: false                  # Ordered list item prefix
MD033: false                  # Allow inline HTML
MD036: false                  # Emphasis used instead of a heading

#################
# Rules by tags #
#################
blank_lines: false  # Error on blank lines
